# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv).

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/u.user")

ParserError: ignored

### Step 3. Assign it to a variable called chipo.

In [ ]:
chipo = df

### Step 4. See the first 10 entries

In [ ]:
chipo.head(10)

  user_id|age|gender|occupation|zip_code
0                1|24|M|technician|85711
1                     2|53|F|other|94043
2                    3|23|M|writer|32067
3                4|24|M|technician|43537
4                     5|33|F|other|15213
5                 6|42|M|executive|98101
6             7|57|M|administrator|91344
7             8|36|M|administrator|05201
8                   9|29|M|student|01002
9                   10|53|M|lawyer|90703

### Step 5. What is the number of observations in the dataset?

In [ ]:
# Solution 1
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   user_id|age|gender|occupation|zip_code  943 non-null    object
dtypes: object(1)
memory usage: 7.5+ KB

In [ ]:
# Solution 2
chipo.shape

(943, 1)

### Step 6. What is the number of columns in the dataset?

In [ ]:
chipo.shape

(943, 1)

### Step 7. Print the name of all the columns.

In [ ]:
print(chipo.columns)

Index(['user_id|age|gender|occupation|zip_code'], dtype='object')

### Step 8. How is the dataset indexed?

In [ ]:
chipo.index

RangeIndex(start=0, stop=943, step=1)

### Step 9. Which was the most-ordered item?

### Step 10. For the most-ordered item, how many items were ordered?

### Step 11. What was the most ordered item in the choice_description column?

### Step 12. How many items were orderd in total?

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

#### Step 13.b. Create a lambda function and change the type of item price

#### Step 13.c. Check the item price type

### Step 14. How much was the revenue for the period in the dataset?

### Step 15. How many orders were made in the period?

### Step 16. What is the average revenue amount per order?

In [ ]:
# Solution 1

In [ ]:
# Solution 2

### Step 17. How many different items are sold?